version: '3.3'

services:
  tubearchivist:
    container_name: tubearchivist
    restart: always
    image: bbilly1/tubearchivist:latest
    ports:
      - 7474:8000
    volumes:
      - /hdd/data/media/youtube:/youtube
      - /home/rocky/docker/tubearchivist/cache:/cache
    environment:
      - ES_URL=http://archivist-es:9200
      - REDIS_HOST=archivist-redis
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=192.168.0.26
      - TA_USERNAME=admin
      - TA_PASSWORD=admin
      - ELASTIC_PASSWORD=admin
      - TZ=Europe/Istanbul
    depends_on:
      - archivist-es
      - archivist-redis

  archivist-redis:
    image: redislabs/rejson:latest
    container_name: archivist-redis
    restart: always
    expose:
      - "6379"
    volumes:
      - /home/rocky/docker/tubearchivist/redis:/data
    depends_on:
      - archivist-es

  archivist-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.1
    container_name: archivist-es
    restart: always
    environment:
      - "xpack.security.enabled=true"
      - "ELASTIC_PASSWORD=admin"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /home/rocky/docker/tubearchivist/es:/usr/share/elasticsearch/data
    expose:
      - "9200"
