version: "3.8"

services:
  app:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    volumes:
      - /home/rocky/docker/uptime-kuma:/app/data
    ports:
      - "3001:3001"
    restart: unless-stopped

  nginx:
    container_name: nginx-reverse-proxy
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
     - /home/rocky/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
