version: "3.8"

services:
  app:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    restart: always
    volumes:
      - /home/debian/docker/uptime-kuma:/app/data
    ports:
      - "3001:3001" 
