version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
      - AUTO_UPDATE=true
    volumes:
      - /hdd/appdata/config/jackett:/config
      - /hdd/data:/data
    ports:
      - 9117:9117
    restart: unless-stopped
    
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    volumes:
      - /hdd/appdata/config/sonarr:/config
      - /hdd/data:/data
    ports:
      - 8989:8989
    restart: unless-stopped
    
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    volumes:
      - /hdd/appdata/config/radarr:/config
      - /hdd/data:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    
  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    volumes:
      - /hdd/appdata/config/bazarr:/config
      - /hdd/data:/data
    ports:
      - 6767:6767
    restart: unless-stopped
    
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
      - WEBUI_PORT=9090
    volumes:
      - /hdd/appdata/config/qbittorrent:/config
      - /hdd/data:/data
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 9090:9090
    restart: unless-stopped
    
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Istanbul
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
 
