version: "3.8"
services:
  dashy:
    container_name: dashy
    image: lissy93/dashy
    volumes:
      - /home/rocky/docker/dashy/public/conf.yml:/app/public/conf.yml
      - /home/rocky/docker/dashy/public/item-icons:/app/public/item-icons
    ports:
      - 4000:80
    environment:
      - NODE_ENV=production
      - UID=1000
      - GID=1000
    restart: unless-stopped
